const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

const PROJECT_ROOT = path.resolve(__dirname, '../../');
console.log('Running Empirical Challenger Verification Script for Milestone 2...');
console.log('Project Root:', PROJECT_ROOT);

const findings = [];

// Helper to log findings
function recordFinding(category, severity, title, description) {
  findings.push({ category, severity, title, description });
  console.log(`[${severity}] (${category}) ${title}: ${description}`);
}

// ----------------------------------------------------
// 1. Build Verification & Dist Asset Inspection
// ----------------------------------------------------
console.log('\n--- 1. Testing Vite Production Build ---');
try {
  const buildOutput = execSync('npm run build', { cwd: PROJECT_ROOT, encoding: 'utf8' });
  console.log('Vite build output summary:\n', buildOutput.split('\n').filter(l => l.includes('dist/')).join('\n'));
  
  const distDir = path.join(PROJECT_ROOT, 'dist');
  if (!fs.existsSync(distDir)) {
    recordFinding('Build', 'HIGH', 'Dist folder missing', 'The dist folder was not generated by Vite build.');
  } else {
    const assetsDir = path.join(distDir, 'assets');
    const assetFiles = fs.readdirSync(assetsDir);
    const cssFile = assetFiles.find(f => f.endsWith('.css'));
    const jsFile = assetFiles.find(f => f.endsWith('.js'));
    
    if (!cssFile || !jsFile) {
      recordFinding('Build', 'HIGH', 'Missing Bundle Assets', 'CSS or JS bundle asset missing in dist/assets.');
    } else {
      console.log(`[PASS] Bundle assets generated: CSS (${cssFile}), JS (${jsFile})`);
      
      // Read CSS output to check compiled rules
      const cssContent = fs.readFileSync(path.join(assetsDir, cssFile), 'utf8');
      
      // Check if custom colors exist in CSS
      if (!cssContent.includes('#4E6E58') && !cssContent.includes('4e6e58')) {
        recordFinding('Theme', 'HIGH', 'Sage-500 Color Missing', 'Primary accent Sage #4E6E58 was not compiled into CSS.');
      }
      if (!cssContent.includes('#D97757') && !cssContent.includes('d97757')) {
        recordFinding('Theme', 'HIGH', 'Terracotta-500 Color Missing', 'Secondary accent Terracotta #D97757 was not compiled into CSS.');
      }
      if (!cssContent.includes('#FAF8F5') && !cssContent.includes('faf8f5')) {
        recordFinding('Theme', 'HIGH', 'Warm Cream Color Missing', 'Warm Cream #FAF8F5 was not compiled into CSS.');
      }
    }
  }
} catch (err) {
  recordFinding('Build', 'CRITICAL', 'Vite Build Error', err.message);
}

// ----------------------------------------------------
// 2. Code Inspection & Syntax Analysis
// ----------------------------------------------------
console.log('\n--- 2. Checking Code for Bugs & Edge Cases ---');

// Check DogProfilesView.jsx for JSON.parse on triggers
const dogProfilesPath = path.join(PROJECT_ROOT, 'src/components/profiles/DogProfilesView.jsx');
if (fs.existsSync(dogProfilesPath)) {
  const content = fs.readFileSync(dogProfilesPath, 'utf8');
  if (content.includes('JSON.parse(') && !content.includes('try') && !content.includes('catch')) {
    recordFinding('State/Robustness', 'MEDIUM', 'Unsafe JSON.parse in DogProfilesView', 
      'dog.triggers is parsed with JSON.parse without try/catch block. If triggers contains raw non-JSON text, rendering will crash with SyntaxError.');
  }
}

// Check Header.jsx for invalid Tailwind class h-18
const headerPath = path.join(PROJECT_ROOT, 'src/components/layout/Header.jsx');
if (fs.existsSync(headerPath)) {
  const content = fs.readFileSync(headerPath, 'utf8');
  if (content.includes('h-18')) {
    recordFinding('CSS/Tailwind', 'LOW', 'Non-standard Tailwind Class `h-18`', 
      'Header.jsx uses `h-18` which is not a standard Tailwind v3 class nor defined in tailwind.config.js spacing/height rules.');
  }
}

// Check Modal.jsx for accessibility (role, focus trap, body scroll lock)
const modalPath = path.join(PROJECT_ROOT, 'src/components/common/Modal.jsx');
if (fs.existsSync(modalPath)) {
  const content = fs.readFileSync(modalPath, 'utf8');
  if (!content.includes('role="dialog"') && !content.includes('role=\'dialog\'')) {
    recordFinding('Accessibility', 'MEDIUM', 'Missing ARIA role in Modal', 
      'Modal card lacks role="dialog" or aria-modal="true" for screen readers.');
  }
  if (!content.includes('document.body.style.overflow')) {
    recordFinding('Accessibility', 'LOW', 'Missing Body Scroll Lock in Modal', 
      'Modal does not disable document.body overflow scrolling when open.');
  }
  if (!content.includes('focus') && !content.includes('useRef')) {
    recordFinding('Accessibility', 'MEDIUM', 'Missing Focus Trap & Restoration in Modal', 
      'Modal does not lock focus inside the dialog or focus the first element on open / restore focus on close.');
  }
}

// Check AppContext.jsx for unhandled promise rejections or missing state
const appContextPath = path.join(PROJECT_ROOT, 'src/context/AppContext.jsx');
if (fs.existsSync(appContextPath)) {
  const content = fs.readFileSync(appContextPath, 'utf8');
  // Inspect error handling
  if (content.includes('loadWalks') && !content.includes('setError(')) {
    // check loadWalks function specifically
    const loadWalksMatch = content.match(/const loadWalks[\s\S]*?\};/);
    if (loadWalksMatch && !loadWalksMatch[0].includes('setError')) {
      recordFinding('API/ErrorHandling', 'LOW', 'Silent loadWalks failure', 
        'loadWalks catches API error with console.warn, but does not surface user-visible error state.');
    }
  }
}

// ----------------------------------------------------
// 3. Class Name Scan across JSX files
// ----------------------------------------------------
console.log('\n--- 3. Scanning JSX files for undefined or suspicious utility classes ---');
function getAllJsxFiles(dir) {
  let files = [];
  fs.readdirSync(dir).forEach(file => {
    const fullPath = path.join(dir, file);
    if (fs.statSync(fullPath).isDirectory()) {
      files = files.concat(getAllJsxFiles(fullPath));
    } else if (file.endsWith('.jsx')) {
      files.push(fullPath);
    }
  });
  return files;
}

const jsxFiles = getAllJsxFiles(path.join(PROJECT_ROOT, 'src'));
console.log(`Found ${jsxFiles.length} JSX files.`);

// Summary of Findings
console.log('\n=============================================');
console.log(`VERIFICATION COMPLETE: Found ${findings.length} issue(s).`);
fs.writeFileSync(
  path.join(__dirname, 'verification_summary.json'),
  JSON.stringify(findings, null, 2)
);
